### ISSUE TITLE
Incorrect title for README.md in slides repo?

### ISSUE THREAD

**Issue by yarwelp** [cis198-2016f/slides#1]
I noticed that the slides repo README.md has title "CIS 198 Homework - Fall 2016", which is also the title of README.md in the homework repo. Probably the README.md in the slides repo should say "CIS 198 Slides - Fall 2016" or something like that. It's a _really_ minor issue but I noticed it and thought I'd let you know.

**Comment by terryxsun** [comment]
DERP. Thanks!
