### ISSUE TITLE
Slide 37 from lecture 02 looks a bit strange

### ISSUE THREAD

**Issue by yarwelp** [cis198-2016f/slides#4]
The final six lines of the code fragment given is:

``` rust
let p = Pizza(vec![1, 2, 3, 4]);
{
    let s = PizzaSlice { pizza: &p, index: 1 };
    let mut c = PizzaConsumer { slice: s, pizza: &p };
    get_another_slice(&mut c, 2);
}
```

Is this intended to actually be:

``` rust
fn main() {
    let p = Pizza(vec![1, 2, 3, 4]);
    let s = PizzaSlice { pizza: &p, index: 1 };
    let mut c = PizzaConsumer { slice: s, pizza: &p };
    get_another_slice(&mut c, 2);
}
```

or is there something else going on that I am missing and it's intended to look like it does?

**Comment by terryxsun** [comment]
It's intentional (although it should be in `main` -- that's missing so it fits int he slide). The extra set of braces is to create an inner scope which will end (thus dropping s and c) before the main scope (when p drops).
